### ISSUE TITLE
Parse object identifier encoded in DER

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/blockchain-attestation#8]
I always prefer to break down projects into very fine small tasks.

Require to decode an object identifier in DER format with a minimum amount of gas, use op_codes if necessary.

Test case 1:

DER encoded `06 06 2a 86 48 86 f7 0d` should parse to: `1.2.840.113549`, which is a shorthand for:

    value1: 1
    value2: 2
    value3: 840
    value4: 113549

Relevant rule copied from an ASN.1 intro: http://luca.ntop.org/Teaching/Appunti/asn1.html

> The first octet has value 40 * value1 + value2. (This is unambiguous, since value1 is limited to values 0, 1, and 2; value2 is limited to the range 0 to 39 when value1 is 0 or 1; and, according to X.208, n is always at least 2.)
> The following octets, if any, encode value3, ..., valuen. Each value is encoded base 128, most significant digit first, with as few digits as possible, and the most significant bit of each octet except the last in the value's encoding set to "1."

> Example: The first octet of the BER encoding of RSA Data Security, Inc.'s object identifier is 40 * 1 + 2 = 42 = 2a16. The encoding of 840 = 6 * 128 + 4816 is 86 48 and the encoding of 113549 = 6 * 1282 + 7716 * 128 + d16 is 86 f7 0d. This leads to the following BER encoding:

> `06 06 2a 86 48 86 f7 0d`

Test case 2:

Look at our XML used in FIFA WC tokens:
https://github.com/alpha-wallet/contracts/blob/master/FIFA%20WC2018/schema1/TicketingContract.xml

Observe the "locality" attribute having OID "2.5.4.7"

    <attribute-type id="locality" oid="2.5.4.7" syntax="1.3.6.1.4.1.1466.115.121.1.15">
      <name lang="en">City</name>
      <name lang="zh">城市</name>
      <name lang="es">Ciudad</name>
      <name lang="ru">город</name>

Encode the OID in DER by hand and decode it in a smart-contract.

**Comment by JamesSmartCell** [comment]
Makes total sense - I'll check it.

**Comment by jot2re** [comment]
Note that the  first `06 06` indicates that what follows is an object identifier, consisting of 6 octets.  That is, the first byte indicates that what is encoded is of the type `object identifier` and the second byte indicates the amount of octets following (in this case 6). See the rules in [section 3](http://luca.ntop.org/Teaching/Appunti/asn1.html) for details.

**Comment by colourful-land** [comment]
James Brown provided the code:

[DerDecode.sol.gz](https://github.com/AlphaWallet/blockchain-attestation/files/3845526/DerDecode.sol.gz)
